
 console.log(a);

 var a = 6;

 console.log(a);
 greeting()

 function greeting(){
  console.log("Good Morning");
 }

 //Hoisting is the Process where interpreter will moves the Declaration of functions and declarations of variables to the top of the scope 
//  before executing the code
 //functions variables will be made available even before declaring and 
 //Variables declarations will be made undefined
//JS hoists only declarations and not initialization

//Hoisting with let and const --> Error -> cannot access variable before declartion

